name: app-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          extensions: pdo, sqlite3, pdo_pgsql, xdebug
      - name: Install dependencies
        run: make install

      - name: Set up environment variables
        run: |
          echo "APP_ENV=local" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_DATABASE=${{ secrets.DATABASE }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_DATABASE: ${{ secrets.DATABASE }}
          APP_URL: ${{ secrets.APP_URL }}

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}

        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workspace}}/build/logs/clover.xml:clover
